# attach required libraries
require(sp)
require(FLCore)
require(RODBC)
# require(fields)
require(alphahull)
require(rgeos)
require(icesAdvice)
require(beanplot)
require(raster)
require(maptools)
require(mapdata)
require(rgdal)
require(plyr)
require(dplyr)
require(tidyr, exclude="expand")
require(icesTAF)